### ISSUE TITLE
Great idea for a program

### ISSUE THREAD

**Issue by samrocketman** [justincampbell/plop#1]
Very handy.  Since I typically want a quick setup on unix-y environments I converted your idea to a bash script.

https://github.com/samrocketman/home/blob/master/bin/plop

Notes about bash:
- The first program that waits reading on stdin is linked up to the whole script's stdin.  That's why that cat command works.

That bash script can basically be summarized into 3 lines using environment vars instead of options.

``` bash
#!/bin/bash
plop_file="$(mktemp "${plop_tmp_dir:-/tmp}/${plop_tmp_file:-plop}-XXXXXXXX")"
cat > "${plop_file}"
echo "${plop_file}"
```

Or as a function in `.bashrc`.

``` bash
function plop() (
  plop_file="$(mktemp "${plop_tmp_dir:-/tmp}/${plop_tmp_file:-plop}-XXXXXXXX")"
  cat > "${plop_file}"
  echo "${plop_file}"
)
```

A function surrounded by parens `()` instead of curly brackets `{}` will subshell.

**Comment by justincampbell** [comment]
Awesome! I'll add a link to the README.

**Comment by samrocketman** [comment]
Feel free to just link this issue for extra context.
